import Head from 'next/head'
import { FC, useState } from 'react'
import { DashboardLayout, MainColumn, SideColumn } from '../components/dashboardLayout'
import StepTrackerPanel from '../components/stepTrackerPanel'
import WaterIntakePanel from '../components/waterIntakePanel'
import '@fortawesome/fontawesome-svg-core/styles.css'
import SleepLogPanel from '../components/sleepLogPanel'
import WorkoutPanel from '../components/workoutPanel'
import OverviewPanel from '../components/overviewPanel'
import MealPanel from '../components/mealPanel'
import { AuthWrapper } from '@components/authWrapper'
import { useEffect } from 'react'
import { useUserStore } from '@stores/userStore'
import { GetMeals } from '@services/FoodService'
import { Meal } from '@models/Meal'
import moment from 'moment'
import { useDateStore } from '@stores/dateStore'

const Dashboard: FC = () => {
    const [meals, setMeals] = useState<Meal[]>([])
    const { user } = useUserStore((state) => state)
    const { startDate, endDate } = useDateStore((state) => state)

    useEffect(() => {
        ;(async () => {
            if (user) {
                const result = await GetMeals(startDate, endDate, user.id)
                setMeals(result)
            }
        })()
    }, [user])

    return (
        <AuthWrapper>
            <Head>
                <title>BeFit</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/leaf.png" />
            </Head>

            <main>
                <DashboardLayout>
                    <SideColumn>
                        <StepTrackerPanel />
                        <WaterIntakePanel />
                    </SideColumn>
                    <MainColumn>
                        <div className={'flex justify-between'}>
                            <div className={'text-primary font-semibold text-xl'}>Today's overview</div>
                            <div className={'text-wildBlue font-medium text-base'}>
                                {moment(new Date()).format('Do [of] MMMM YYYY')}
                            </div>
                        </div>
                        <OverviewPanel />
                        {meals.map((meal, index) => (
                            <MealPanel key={`meal_${index}_${meal.name}`} meal={meal} />
                        ))}
                    </MainColumn>
                    <SideColumn>
                        <SleepLogPanel />
                        <WorkoutPanel />
                    </SideColumn>
                </DashboardLayout>
                {/*{!loading ? (*/}
                {/*    <h1 className={styles.title}>*/}
                {/*        You have made <strong style={{color: 'emerald'}}>{steps}</strong> steps today!*/}
                {/*    </h1>*/}
                {/*) : (<ClipLoader color="#36d7b7" />)}*/}

                {/*{firebase.user ? <button onClick={logout}>Log out</button> : <button onClick={login}>Log in</button>}*/}
            </main>
        </AuthWrapper>
    )
}

export default Dashboard
