import Head from 'next/head'
import Image from 'next/image'
import { useFirebaseContext } from '../hooks/useFirebase'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { ClipLoader } from 'react-spinners'
import { DashboardLayout, MainColumn, SideColumn } from '../components/dashboardLayout'
import InformationPanel from '../components/informationPanel'
import StepTrackerPanel from '../components/stepTrackerPanel'
import WaterIntakePanel from '../components/waterIntakePanel'
import '@fortawesome/fontawesome-svg-core/styles.css'
import SleepLogPanel from '../components/sleepLogPanel'
import WorkoutPanel from '../components/workoutPanel'
import OverviewPanel from '../components/overviewPanel'
import MealPanel from '../components/mealPanel'
import WorkoutEntry from '../components/workoutEntry'
import MealEntry from '../components/mealEntry'

const Home = () => {
    const { state: firebase, login, logout } = useFirebaseContext()
    const [steps, setSteps] = useState<number>(0)
    const [loading, setLoading] = useState<boolean>(true)

    return (
        <div>
            <Head>
                <title>BeFit</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/leaf.png" />
            </Head>

            <main>
                <DashboardLayout>
                    <SideColumn>
                        {firebase.googleData.steps ? <StepTrackerPanel /> : null}
                        <WaterIntakePanel />
                    </SideColumn>
                    <MainColumn>
                        <div className={'flex justify-between'}>
                            <div className={'text-primary font-semibold text-xl'}>Today's overview</div>
                            <div className={'text-wildBlue font-medium text-base'}>8th of October 2022</div>
                        </div>
                        <OverviewPanel />
                        <MealPanel title={'Breakfast'} subtitle={'288 cal'} icon={'🥐'}>
                            <MealEntry name={'Oatmeal'} calories={'144 calories'} />
                            <MealEntry name={'Oatmeal'} calories={'144 calories'} />
                        </MealPanel>
                        <MealPanel title={'Lunch'} subtitle={'138 cal'} icon={'🥪'}>
                            <MealEntry name={'Burger'} calories={'144 calories'} />
                        </MealPanel>
                        <MealPanel title={'Dinner'} subtitle={'357 cal'} icon={'🍕'}>
                            <MealEntry name={'Burger'} calories={'144 calories'} />
                        </MealPanel>
                        <MealPanel title={'Snacks'} subtitle={'40 cal'} icon={'🍭'}>
                            <MealEntry name={'Burger'} calories={'144 calories'} />
                        </MealPanel>
                    </MainColumn>
                    <SideColumn>
                        <SleepLogPanel />
                        <WorkoutPanel />
                    </SideColumn>
                </DashboardLayout>
                {/*{!loading ? (*/}
                {/*    <h1 className={styles.title}>*/}
                {/*        You have made <strong style={{color: 'emerald'}}>{steps}</strong> steps today!*/}
                {/*    </h1>*/}
                {/*) : (<ClipLoader color="#36d7b7" />)}*/}

                {/*{firebase.user ? <button onClick={logout}>Log out</button> : <button onClick={login}>Log in</button>}*/}
            </main>
        </div>
    )
}

export default Home
